// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: employees.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEmployee = `-- name: CreateEmployee :one
INSERT INTO employees (
  user_id, first_name, last_name, dial_code, phone, resume, country,
  address, state, level, salary_code_id, department, bank_name,
  bank_code, account_number, hired_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16
)
RETURNING id, user_id, first_name, last_name, dial_code, phone, resume, country, address, state, status, level, salary_code_id, department, bank_name, bank_code, account_number, hired_at, updated_at, created_at
`

type CreateEmployeeParams struct {
	UserID        pgtype.UUID      `json:"user_id"`
	FirstName     string           `json:"first_name"`
	LastName      string           `json:"last_name"`
	DialCode      string           `json:"dial_code"`
	Phone         string           `json:"phone"`
	Resume        *string          `json:"resume"`
	Country       *string          `json:"country"`
	Address       *string          `json:"address"`
	State         *string          `json:"state"`
	Level         *string          `json:"level"`
	SalaryCodeID  pgtype.UUID      `json:"salary_code_id"`
	Department    *string          `json:"department"`
	BankName      *string          `json:"bank_name"`
	BankCode      *string          `json:"bank_code"`
	AccountNumber *string          `json:"account_number"`
	HiredAt       pgtype.Timestamp `json:"hired_at"`
}

func (q *Queries) CreateEmployee(ctx context.Context, arg CreateEmployeeParams) (Employee, error) {
	row := q.db.QueryRow(ctx, createEmployee,
		arg.UserID,
		arg.FirstName,
		arg.LastName,
		arg.DialCode,
		arg.Phone,
		arg.Resume,
		arg.Country,
		arg.Address,
		arg.State,
		arg.Level,
		arg.SalaryCodeID,
		arg.Department,
		arg.BankName,
		arg.BankCode,
		arg.AccountNumber,
		arg.HiredAt,
	)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FirstName,
		&i.LastName,
		&i.DialCode,
		&i.Phone,
		&i.Resume,
		&i.Country,
		&i.Address,
		&i.State,
		&i.Status,
		&i.Level,
		&i.SalaryCodeID,
		&i.Department,
		&i.BankName,
		&i.BankCode,
		&i.AccountNumber,
		&i.HiredAt,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteEmployee = `-- name: DeleteEmployee :one
DELETE FROM employees WHERE id = $1
RETURNING id
`

func (q *Queries) DeleteEmployee(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, deleteEmployee, id)
	var id_2 pgtype.UUID
	err := row.Scan(&id_2)
	return id_2, err
}

const getEmployeeByUserID = `-- name: GetEmployeeByUserID :one
SELECT id, user_id, first_name, last_name, dial_code, phone, resume, country, address, state, status, level, salary_code_id, department, bank_name, bank_code, account_number, hired_at, updated_at, created_at FROM employees WHERE user_id = $1
`

func (q *Queries) GetEmployeeByUserID(ctx context.Context, userID pgtype.UUID) (Employee, error) {
	row := q.db.QueryRow(ctx, getEmployeeByUserID, userID)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FirstName,
		&i.LastName,
		&i.DialCode,
		&i.Phone,
		&i.Resume,
		&i.Country,
		&i.Address,
		&i.State,
		&i.Status,
		&i.Level,
		&i.SalaryCodeID,
		&i.Department,
		&i.BankName,
		&i.BankCode,
		&i.AccountNumber,
		&i.HiredAt,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateEmployee = `-- name: UpdateEmployee :one
UPDATE employees SET
  first_name = COALESCE($1, first_name),
  last_name = COALESCE($2, last_name),
  dial_code = COALESCE($3, dial_code),
  phone = COALESCE($4, phone),
  resume = COALESCE($5, resume),
  country = COALESCE($6, country),
  address = COALESCE($7, address),
  state = COALESCE($8, state),
  status = COALESCE($9, status),
  level = COALESCE($10, level),
  salary_code_id = COALESCE($11, salary_code_id),
  department = COALESCE($12, department),
  bank_name = COALESCE($13, bank_name),
  bank_code = COALESCE($14, bank_code),
  account_number = COALESCE($15, account_number),
  hired_at = COALESCE($16, hired_at),
  updated_at = now()
WHERE id = $17
RETURNING id, user_id, first_name, last_name, dial_code, phone, resume, country, address, state, status, level, salary_code_id, department, bank_name, bank_code, account_number, hired_at, updated_at, created_at
`

type UpdateEmployeeParams struct {
	FirstName     *string          `json:"first_name"`
	LastName      *string          `json:"last_name"`
	DialCode      *string          `json:"dial_code"`
	Phone         *string          `json:"phone"`
	Resume        *string          `json:"resume"`
	Country       *string          `json:"country"`
	Address       *string          `json:"address"`
	State         *string          `json:"state"`
	Status        *string          `json:"status"`
	Level         *string          `json:"level"`
	SalaryCodeID  pgtype.UUID      `json:"salary_code_id"`
	Department    *string          `json:"department"`
	BankName      *string          `json:"bank_name"`
	BankCode      *string          `json:"bank_code"`
	AccountNumber *string          `json:"account_number"`
	HiredAt       pgtype.Timestamp `json:"hired_at"`
	ID            pgtype.UUID      `json:"id"`
}

func (q *Queries) UpdateEmployee(ctx context.Context, arg UpdateEmployeeParams) (Employee, error) {
	row := q.db.QueryRow(ctx, updateEmployee,
		arg.FirstName,
		arg.LastName,
		arg.DialCode,
		arg.Phone,
		arg.Resume,
		arg.Country,
		arg.Address,
		arg.State,
		arg.Status,
		arg.Level,
		arg.SalaryCodeID,
		arg.Department,
		arg.BankName,
		arg.BankCode,
		arg.AccountNumber,
		arg.HiredAt,
		arg.ID,
	)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FirstName,
		&i.LastName,
		&i.DialCode,
		&i.Phone,
		&i.Resume,
		&i.Country,
		&i.Address,
		&i.State,
		&i.Status,
		&i.Level,
		&i.SalaryCodeID,
		&i.Department,
		&i.BankName,
		&i.BankCode,
		&i.AccountNumber,
		&i.HiredAt,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}
