// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbq

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Employee struct {
	ID           uuid.UUID `json:"id"`
	UserID       uuid.UUID `json:"user_id"`
	FirstName    string    `json:"first_name"`
	LastName     string    `json:"last_name"`
	DialCode     string    `json:"dial_code"`
	Phone        string    `json:"phone"`
	Resume       *string   `json:"resume"`
	Country      *string   `json:"country"`
	Address      *string   `json:"address"`
	State        *string   `json:"state"`
	Status       string    `json:"status"`
	Level        *string   `json:"level"`
	SalaryCodeID uuid.UUID `json:"salary_code_id"`
	Department   *string   `json:"department"`
	BankName     *string   `json:"bank_name"`
	// Paystack bank code
	BankCode      *string          `json:"bank_code"`
	AccountNumber *string          `json:"account_number"`
	HiredAt       pgtype.Timestamp `json:"hired_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
}

type PaymentRequest struct {
	ID uuid.UUID `json:"id"`
	// procurement team member, FK users.id
	RequestedBy uuid.UUID `json:"requested_by"`
	// CEO who approved/rejected, FK users.id
	ReviewedBy      pgtype.UUID `json:"reviewed_by"`
	Amount          int64       `json:"amount"`
	Status          string      `json:"status"`
	Description     *string     `json:"description"`
	RejectionReason *string     `json:"rejection_reason"`
	// Paystack bank code
	BankCode      *string          `json:"bank_code"`
	AccountNumber *string          `json:"account_number"`
	AccountName   *string          `json:"account_name"`
	ReviewedAt    pgtype.Timestamp `json:"reviewed_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
}

type Payout struct {
	ID           uuid.UUID `json:"id"`
	UserID       uuid.UUID `json:"user_id"`
	SalaryCodeID uuid.UUID `json:"salary_code_id"`
	Amount       int64     `json:"amount"`
	Status       string    `json:"status"`
	// first day of the paid month, e.g. 2026-07-01
	PayPeriod pgtype.Date      `json:"pay_period"`
	PaidAt    pgtype.Timestamp `json:"paid_at"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type SalaryCode struct {
	ID     uuid.UUID `json:"id"`
	Code   string    `json:"code"`
	Level  string    `json:"level"`
	Amount int64     `json:"amount"`
}

type Transaction struct {
	ID               uuid.UUID        `json:"id"`
	WalletID         uuid.UUID        `json:"wallet_id"`
	UserID           uuid.UUID        `json:"user_id"`
	PayoutID         pgtype.UUID      `json:"payout_id"`
	PaymentRequestID pgtype.UUID      `json:"payment_request_id"`
	Amount           int64            `json:"amount"`
	Type             string           `json:"type"`
	Summary          *string          `json:"summary"`
	Provider         *string          `json:"provider"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
}

type User struct {
	ID        uuid.UUID        `json:"id"`
	FirstName string           `json:"first_name"`
	LastName  string           `json:"last_name"`
	Email     string           `json:"email"`
	Password  string           `json:"password"`
	Role      string           `json:"role"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type Wallet struct {
	ID       uuid.UUID `json:"id"`
	Currency string    `json:"currency"`
	// internal ledger balance, source of truth for available funds before disbursing
	Balance   int64            `json:"balance"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type WalletTopup struct {
	ID       uuid.UUID `json:"id"`
	WalletID uuid.UUID `json:"wallet_id"`
	// CEO/admin who funded the wallet, FK users.id
	InitiatedBy uuid.UUID `json:"initiated_by"`
	Amount      int64     `json:"amount"`
	Status      string    `json:"status"`
	// card, bank_transfer, ussd, etc.
	Channel *string `json:"channel"`
	// reference used for Initialize Transaction / Verify Transaction
	PaystackReference *string          `json:"paystack_reference"`
	CompletedAt       pgtype.Timestamp `json:"completed_at"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
}
