// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: payment.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const approvePaymentRequest = `-- name: ApprovePaymentRequest :one
UPDATE payment_requests
SET status = 'approved',
    reviewed_by = $1,
    reviewed_at = now(),
    updated_at = now()
WHERE id = $2 AND status = 'pending'
RETURNING id, requested_by, reviewed_by, amount, status, description, rejection_reason, bank_code, account_number, account_name, reviewed_at, updated_at, created_at
`

type ApprovePaymentRequestParams struct {
	ReviewedBy pgtype.UUID `json:"reviewed_by"`
	ID         pgtype.UUID `json:"id"`
}

// Only a pending request can be approved (guards double-processing).
func (q *Queries) ApprovePaymentRequest(ctx context.Context, arg ApprovePaymentRequestParams) (PaymentRequest, error) {
	row := q.db.QueryRow(ctx, approvePaymentRequest, arg.ReviewedBy, arg.ID)
	var i PaymentRequest
	err := row.Scan(
		&i.ID,
		&i.RequestedBy,
		&i.ReviewedBy,
		&i.Amount,
		&i.Status,
		&i.Description,
		&i.RejectionReason,
		&i.BankCode,
		&i.AccountNumber,
		&i.AccountName,
		&i.ReviewedAt,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const countPaymentRequests = `-- name: CountPaymentRequests :one
SELECT COUNT(*) FROM payment_requests
WHERE ($1::text IS NULL OR status = $1)
  AND ($2::uuid IS NULL OR requested_by = $2)
`

type CountPaymentRequestsParams struct {
	Status      *string     `json:"status"`
	RequestedBy pgtype.UUID `json:"requested_by"`
}

func (q *Queries) CountPaymentRequests(ctx context.Context, arg CountPaymentRequestsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPaymentRequests, arg.Status, arg.RequestedBy)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPayouts = `-- name: CountPayouts :one
SELECT COUNT(*) FROM payouts
WHERE ($1::uuid IS NULL OR user_id = $1)
  AND ($2::text IS NULL OR status = $2)
  AND ($3::date IS NULL OR pay_period = $3)
`

type CountPayoutsParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	Status    *string     `json:"status"`
	PayPeriod pgtype.Date `json:"pay_period"`
}

func (q *Queries) CountPayouts(ctx context.Context, arg CountPayoutsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPayouts, arg.UserID, arg.Status, arg.PayPeriod)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPayoutsByEmployee = `-- name: CountPayoutsByEmployee :one
SELECT COUNT(*) FROM payouts WHERE user_id = $1
`

func (q *Queries) CountPayoutsByEmployee(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPayoutsByEmployee, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTransactions = `-- name: CountTransactions :one
SELECT COUNT(*) FROM transactions
WHERE ($1::uuid IS NULL OR wallet_id = $1)
  AND ($2::uuid IS NULL OR user_id = $2)
  AND ($3::text IS NULL OR type = $3)
  AND ($4::timestamp IS NULL OR created_at >= $4)
  AND ($5::timestamp IS NULL OR created_at <= $5)
`

type CountTransactionsParams struct {
	WalletID pgtype.UUID      `json:"wallet_id"`
	UserID   pgtype.UUID      `json:"user_id"`
	Type     *string          `json:"type"`
	Start    pgtype.Timestamp `json:"start"`
	End      pgtype.Timestamp `json:"end"`
}

func (q *Queries) CountTransactions(ctx context.Context, arg CountTransactionsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTransactions,
		arg.WalletID,
		arg.UserID,
		arg.Type,
		arg.Start,
		arg.End,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countWalletTopups = `-- name: CountWalletTopups :one
SELECT COUNT(*) FROM wallet_topups
WHERE ($1::text IS NULL OR status = $1)
  AND ($2::uuid IS NULL OR initiated_by = $2)
`

type CountWalletTopupsParams struct {
	Status      *string     `json:"status"`
	InitiatedBy pgtype.UUID `json:"initiated_by"`
}

func (q *Queries) CountWalletTopups(ctx context.Context, arg CountWalletTopupsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countWalletTopups, arg.Status, arg.InitiatedBy)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPaymentRequest = `-- name: CreatePaymentRequest :one

INSERT INTO payment_requests (
  requested_by, amount, description, bank_code, account_number, account_name
) VALUES (
  $1, $2, $3, $4, $5, $6
)
RETURNING id, requested_by, reviewed_by, amount, status, description, rejection_reason, bank_code, account_number, account_name, reviewed_at, updated_at, created_at
`

type CreatePaymentRequestParams struct {
	RequestedBy   pgtype.UUID `json:"requested_by"`
	Amount        int64       `json:"amount"`
	Description   *string     `json:"description"`
	BankCode      *string     `json:"bank_code"`
	AccountNumber *string     `json:"account_number"`
	AccountName   *string     `json:"account_name"`
}

// ============================================================
// Payment requests (procurement -> CEO review)
// ============================================================
func (q *Queries) CreatePaymentRequest(ctx context.Context, arg CreatePaymentRequestParams) (PaymentRequest, error) {
	row := q.db.QueryRow(ctx, createPaymentRequest,
		arg.RequestedBy,
		arg.Amount,
		arg.Description,
		arg.BankCode,
		arg.AccountNumber,
		arg.AccountName,
	)
	var i PaymentRequest
	err := row.Scan(
		&i.ID,
		&i.RequestedBy,
		&i.ReviewedBy,
		&i.Amount,
		&i.Status,
		&i.Description,
		&i.RejectionReason,
		&i.BankCode,
		&i.AccountNumber,
		&i.AccountName,
		&i.ReviewedAt,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createPayout = `-- name: CreatePayout :one

INSERT INTO payouts (user_id, salary_code_id, amount, pay_period, status)
VALUES ($1, $2, $3, $4, COALESCE($5, 'pending'))
RETURNING id, user_id, salary_code_id, amount, status, pay_period, paid_at, created_at
`

type CreatePayoutParams struct {
	UserID       pgtype.UUID `json:"user_id"`
	SalaryCodeID pgtype.UUID `json:"salary_code_id"`
	Amount       int64       `json:"amount"`
	PayPeriod    pgtype.Date `json:"pay_period"`
	Status       interface{} `json:"status"`
}

// ============================================================
// Payouts (salary disbursement)
// ============================================================
func (q *Queries) CreatePayout(ctx context.Context, arg CreatePayoutParams) (Payout, error) {
	row := q.db.QueryRow(ctx, createPayout,
		arg.UserID,
		arg.SalaryCodeID,
		arg.Amount,
		arg.PayPeriod,
		arg.Status,
	)
	var i Payout
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SalaryCodeID,
		&i.Amount,
		&i.Status,
		&i.PayPeriod,
		&i.PaidAt,
		&i.CreatedAt,
	)
	return i, err
}

const createTransaction = `-- name: CreateTransaction :one

INSERT INTO transactions (
  wallet_id, user_id, payout_id, payment_request_id, amount, type, summary, provider
) VALUES (
  $1, $2, $5, $6, $3, $4, $7, $8
)
RETURNING id, wallet_id, user_id, payout_id, payment_request_id, amount, type, summary, provider, created_at
`

type CreateTransactionParams struct {
	WalletID         pgtype.UUID `json:"wallet_id"`
	UserID           pgtype.UUID `json:"user_id"`
	Amount           int64       `json:"amount"`
	Type             string      `json:"type"`
	PayoutID         pgtype.UUID `json:"payout_id"`
	PaymentRequestID pgtype.UUID `json:"payment_request_id"`
	Summary          *string     `json:"summary"`
	Provider         *string     `json:"provider"`
}

// ============================================================
// Transactions (immutable ledger)
// ============================================================
func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.WalletID,
		arg.UserID,
		arg.Amount,
		arg.Type,
		arg.PayoutID,
		arg.PaymentRequestID,
		arg.Summary,
		arg.Provider,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.UserID,
		&i.PayoutID,
		&i.PaymentRequestID,
		&i.Amount,
		&i.Type,
		&i.Summary,
		&i.Provider,
		&i.CreatedAt,
	)
	return i, err
}

const createWallet = `-- name: CreateWallet :one

INSERT INTO wallets (currency)
VALUES (COALESCE($1, 'NGN'))
RETURNING id, currency, balance, updated_at, created_at
`

// ============================================================
// Wallet
// ============================================================
func (q *Queries) CreateWallet(ctx context.Context, currency interface{}) (Wallet, error) {
	row := q.db.QueryRow(ctx, createWallet, currency)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.Currency,
		&i.Balance,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createWalletTopup = `-- name: CreateWalletTopup :one

INSERT INTO wallet_topups (
  wallet_id, initiated_by, amount, status, channel, paystack_reference
) VALUES (
  $1, $2, $3, COALESCE($4, 'pending'), $5, $6
)
RETURNING id, wallet_id, initiated_by, amount, status, channel, paystack_reference, completed_at, created_at
`

type CreateWalletTopupParams struct {
	WalletID          pgtype.UUID `json:"wallet_id"`
	InitiatedBy       pgtype.UUID `json:"initiated_by"`
	Amount            int64       `json:"amount"`
	Status            interface{} `json:"status"`
	Channel           *string     `json:"channel"`
	PaystackReference *string     `json:"paystack_reference"`
}

// ============================================================
// Wallet top-ups (add money)
// ============================================================
func (q *Queries) CreateWalletTopup(ctx context.Context, arg CreateWalletTopupParams) (WalletTopup, error) {
	row := q.db.QueryRow(ctx, createWalletTopup,
		arg.WalletID,
		arg.InitiatedBy,
		arg.Amount,
		arg.Status,
		arg.Channel,
		arg.PaystackReference,
	)
	var i WalletTopup
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.InitiatedBy,
		&i.Amount,
		&i.Status,
		&i.Channel,
		&i.PaystackReference,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const creditWallet = `-- name: CreditWallet :one
UPDATE wallets
SET balance = balance + $1,
    updated_at = now()
WHERE id = $2
RETURNING id, currency, balance, updated_at, created_at
`

type CreditWalletParams struct {
	Amount int64       `json:"amount"`
	ID     pgtype.UUID `json:"id"`
}

func (q *Queries) CreditWallet(ctx context.Context, arg CreditWalletParams) (Wallet, error) {
	row := q.db.QueryRow(ctx, creditWallet, arg.Amount, arg.ID)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.Currency,
		&i.Balance,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const debitWallet = `-- name: DebitWallet :one
UPDATE wallets
SET balance = balance - $1,
    updated_at = now()
WHERE id = $2
  AND balance >= $1
RETURNING id, currency, balance, updated_at, created_at
`

type DebitWalletParams struct {
	Amount int64       `json:"amount"`
	ID     pgtype.UUID `json:"id"`
}

// Atomic guarded debit: returns no row when funds are insufficient, so the
// caller can treat pgx.ErrNoRows as "insufficient funds".
func (q *Queries) DebitWallet(ctx context.Context, arg DebitWalletParams) (Wallet, error) {
	row := q.db.QueryRow(ctx, debitWallet, arg.Amount, arg.ID)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.Currency,
		&i.Balance,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPaymentRequestByID = `-- name: GetPaymentRequestByID :one
SELECT id, requested_by, reviewed_by, amount, status, description, rejection_reason, bank_code, account_number, account_name, reviewed_at, updated_at, created_at FROM payment_requests WHERE id = $1
`

func (q *Queries) GetPaymentRequestByID(ctx context.Context, id pgtype.UUID) (PaymentRequest, error) {
	row := q.db.QueryRow(ctx, getPaymentRequestByID, id)
	var i PaymentRequest
	err := row.Scan(
		&i.ID,
		&i.RequestedBy,
		&i.ReviewedBy,
		&i.Amount,
		&i.Status,
		&i.Description,
		&i.RejectionReason,
		&i.BankCode,
		&i.AccountNumber,
		&i.AccountName,
		&i.ReviewedAt,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPayoutByID = `-- name: GetPayoutByID :one
SELECT id, user_id, salary_code_id, amount, status, pay_period, paid_at, created_at FROM payouts WHERE id = $1
`

func (q *Queries) GetPayoutByID(ctx context.Context, id pgtype.UUID) (Payout, error) {
	row := q.db.QueryRow(ctx, getPayoutByID, id)
	var i Payout
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SalaryCodeID,
		&i.Amount,
		&i.Status,
		&i.PayPeriod,
		&i.PaidAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPayoutByUserAndPeriod = `-- name: GetPayoutByUserAndPeriod :one
SELECT id, user_id, salary_code_id, amount, status, pay_period, paid_at, created_at FROM payouts WHERE user_id = $1 AND pay_period = $2
`

type GetPayoutByUserAndPeriodParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	PayPeriod pgtype.Date `json:"pay_period"`
}

// Idempotency guard for the monthly batch.
func (q *Queries) GetPayoutByUserAndPeriod(ctx context.Context, arg GetPayoutByUserAndPeriodParams) (Payout, error) {
	row := q.db.QueryRow(ctx, getPayoutByUserAndPeriod, arg.UserID, arg.PayPeriod)
	var i Payout
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SalaryCodeID,
		&i.Amount,
		&i.Status,
		&i.PayPeriod,
		&i.PaidAt,
		&i.CreatedAt,
	)
	return i, err
}

const getTransactionByID = `-- name: GetTransactionByID :one
SELECT id, wallet_id, user_id, payout_id, payment_request_id, amount, type, summary, provider, created_at FROM transactions WHERE id = $1
`

func (q *Queries) GetTransactionByID(ctx context.Context, id pgtype.UUID) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransactionByID, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.UserID,
		&i.PayoutID,
		&i.PaymentRequestID,
		&i.Amount,
		&i.Type,
		&i.Summary,
		&i.Provider,
		&i.CreatedAt,
	)
	return i, err
}

const getWallet = `-- name: GetWallet :one
SELECT id, currency, balance, updated_at, created_at FROM wallets
ORDER BY created_at ASC
LIMIT 1
`

// The system runs a single wallet; grab the earliest-created one.
func (q *Queries) GetWallet(ctx context.Context) (Wallet, error) {
	row := q.db.QueryRow(ctx, getWallet)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.Currency,
		&i.Balance,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getWalletByID = `-- name: GetWalletByID :one
SELECT id, currency, balance, updated_at, created_at FROM wallets WHERE id = $1
`

func (q *Queries) GetWalletByID(ctx context.Context, id pgtype.UUID) (Wallet, error) {
	row := q.db.QueryRow(ctx, getWalletByID, id)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.Currency,
		&i.Balance,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getWalletForUpdate = `-- name: GetWalletForUpdate :one
SELECT id, currency, balance, updated_at, created_at FROM wallets WHERE id = $1 FOR UPDATE
`

// Row-lock the wallet inside a transaction before mutating the balance.
func (q *Queries) GetWalletForUpdate(ctx context.Context, id pgtype.UUID) (Wallet, error) {
	row := q.db.QueryRow(ctx, getWalletForUpdate, id)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.Currency,
		&i.Balance,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getWalletTopupByID = `-- name: GetWalletTopupByID :one
SELECT id, wallet_id, initiated_by, amount, status, channel, paystack_reference, completed_at, created_at FROM wallet_topups WHERE id = $1
`

func (q *Queries) GetWalletTopupByID(ctx context.Context, id pgtype.UUID) (WalletTopup, error) {
	row := q.db.QueryRow(ctx, getWalletTopupByID, id)
	var i WalletTopup
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.InitiatedBy,
		&i.Amount,
		&i.Status,
		&i.Channel,
		&i.PaystackReference,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getWalletTopupByReference = `-- name: GetWalletTopupByReference :one
SELECT id, wallet_id, initiated_by, amount, status, channel, paystack_reference, completed_at, created_at FROM wallet_topups WHERE paystack_reference = $1
`

func (q *Queries) GetWalletTopupByReference(ctx context.Context, paystackReference *string) (WalletTopup, error) {
	row := q.db.QueryRow(ctx, getWalletTopupByReference, paystackReference)
	var i WalletTopup
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.InitiatedBy,
		&i.Amount,
		&i.Status,
		&i.Channel,
		&i.PaystackReference,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listPaymentRequests = `-- name: ListPaymentRequests :many
SELECT id, requested_by, reviewed_by, amount, status, description, rejection_reason, bank_code, account_number, account_name, reviewed_at, updated_at, created_at FROM payment_requests
WHERE ($3::text IS NULL OR status = $3)
  AND ($4::uuid IS NULL OR requested_by = $4)
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListPaymentRequestsParams struct {
	Limit       int32       `json:"limit"`
	Offset      int32       `json:"offset"`
	Status      *string     `json:"status"`
	RequestedBy pgtype.UUID `json:"requested_by"`
}

func (q *Queries) ListPaymentRequests(ctx context.Context, arg ListPaymentRequestsParams) ([]PaymentRequest, error) {
	rows, err := q.db.Query(ctx, listPaymentRequests,
		arg.Limit,
		arg.Offset,
		arg.Status,
		arg.RequestedBy,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PaymentRequest{}
	for rows.Next() {
		var i PaymentRequest
		if err := rows.Scan(
			&i.ID,
			&i.RequestedBy,
			&i.ReviewedBy,
			&i.Amount,
			&i.Status,
			&i.Description,
			&i.RejectionReason,
			&i.BankCode,
			&i.AccountNumber,
			&i.AccountName,
			&i.ReviewedAt,
			&i.UpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPayouts = `-- name: ListPayouts :many
SELECT id, user_id, salary_code_id, amount, status, pay_period, paid_at, created_at FROM payouts
WHERE ($3::uuid IS NULL OR user_id = $3)
  AND ($4::text IS NULL OR status = $4)
  AND ($5::date IS NULL OR pay_period = $5)
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListPayoutsParams struct {
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
	UserID    pgtype.UUID `json:"user_id"`
	Status    *string     `json:"status"`
	PayPeriod pgtype.Date `json:"pay_period"`
}

func (q *Queries) ListPayouts(ctx context.Context, arg ListPayoutsParams) ([]Payout, error) {
	rows, err := q.db.Query(ctx, listPayouts,
		arg.Limit,
		arg.Offset,
		arg.UserID,
		arg.Status,
		arg.PayPeriod,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Payout{}
	for rows.Next() {
		var i Payout
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SalaryCodeID,
			&i.Amount,
			&i.Status,
			&i.PayPeriod,
			&i.PaidAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPayoutsByEmployee = `-- name: ListPayoutsByEmployee :many
SELECT id, user_id, salary_code_id, amount, status, pay_period, paid_at, created_at FROM payouts
WHERE user_id = $1
ORDER BY pay_period DESC
LIMIT $2 OFFSET $3
`

type ListPayoutsByEmployeeParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

// An employee's own payout history (GET /employees/:id/payouts).
func (q *Queries) ListPayoutsByEmployee(ctx context.Context, arg ListPayoutsByEmployeeParams) ([]Payout, error) {
	rows, err := q.db.Query(ctx, listPayoutsByEmployee, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Payout{}
	for rows.Next() {
		var i Payout
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SalaryCodeID,
			&i.Amount,
			&i.Status,
			&i.PayPeriod,
			&i.PaidAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactions = `-- name: ListTransactions :many
SELECT id, wallet_id, user_id, payout_id, payment_request_id, amount, type, summary, provider, created_at FROM transactions
WHERE ($3::uuid IS NULL OR wallet_id = $3)
  AND ($4::uuid IS NULL OR user_id = $4)
  AND ($5::text IS NULL OR type = $5)
  AND ($6::timestamp IS NULL OR created_at >= $6)
  AND ($7::timestamp IS NULL OR created_at <= $7)
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListTransactionsParams struct {
	Limit    int32            `json:"limit"`
	Offset   int32            `json:"offset"`
	WalletID pgtype.UUID      `json:"wallet_id"`
	UserID   pgtype.UUID      `json:"user_id"`
	Type     *string          `json:"type"`
	Start    pgtype.Timestamp `json:"start"`
	End      pgtype.Timestamp `json:"end"`
}

func (q *Queries) ListTransactions(ctx context.Context, arg ListTransactionsParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listTransactions,
		arg.Limit,
		arg.Offset,
		arg.WalletID,
		arg.UserID,
		arg.Type,
		arg.Start,
		arg.End,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.WalletID,
			&i.UserID,
			&i.PayoutID,
			&i.PaymentRequestID,
			&i.Amount,
			&i.Type,
			&i.Summary,
			&i.Provider,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWalletTopups = `-- name: ListWalletTopups :many
SELECT id, wallet_id, initiated_by, amount, status, channel, paystack_reference, completed_at, created_at FROM wallet_topups
WHERE ($3::text IS NULL OR status = $3)
  AND ($4::uuid IS NULL OR initiated_by = $4)
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListWalletTopupsParams struct {
	Limit       int32       `json:"limit"`
	Offset      int32       `json:"offset"`
	Status      *string     `json:"status"`
	InitiatedBy pgtype.UUID `json:"initiated_by"`
}

func (q *Queries) ListWalletTopups(ctx context.Context, arg ListWalletTopupsParams) ([]WalletTopup, error) {
	rows, err := q.db.Query(ctx, listWalletTopups,
		arg.Limit,
		arg.Offset,
		arg.Status,
		arg.InitiatedBy,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WalletTopup{}
	for rows.Next() {
		var i WalletTopup
		if err := rows.Scan(
			&i.ID,
			&i.WalletID,
			&i.InitiatedBy,
			&i.Amount,
			&i.Status,
			&i.Channel,
			&i.PaystackReference,
			&i.CompletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markWalletTopupStatus = `-- name: MarkWalletTopupStatus :one
UPDATE wallet_topups
SET status = $1,
    channel = COALESCE($2, channel),
    completed_at = CASE WHEN $1 IN ('success', 'failed') THEN now() ELSE completed_at END
WHERE id = $3
RETURNING id, wallet_id, initiated_by, amount, status, channel, paystack_reference, completed_at, created_at
`

type MarkWalletTopupStatusParams struct {
	Status  string      `json:"status"`
	Channel *string     `json:"channel"`
	ID      pgtype.UUID `json:"id"`
}

func (q *Queries) MarkWalletTopupStatus(ctx context.Context, arg MarkWalletTopupStatusParams) (WalletTopup, error) {
	row := q.db.QueryRow(ctx, markWalletTopupStatus, arg.Status, arg.Channel, arg.ID)
	var i WalletTopup
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.InitiatedBy,
		&i.Amount,
		&i.Status,
		&i.Channel,
		&i.PaystackReference,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const rejectPaymentRequest = `-- name: RejectPaymentRequest :one
UPDATE payment_requests
SET status = 'rejected',
    rejection_reason = $1,
    reviewed_by = $2,
    reviewed_at = now(),
    updated_at = now()
WHERE id = $3 AND status = 'pending'
RETURNING id, requested_by, reviewed_by, amount, status, description, rejection_reason, bank_code, account_number, account_name, reviewed_at, updated_at, created_at
`

type RejectPaymentRequestParams struct {
	RejectionReason *string     `json:"rejection_reason"`
	ReviewedBy      pgtype.UUID `json:"reviewed_by"`
	ID              pgtype.UUID `json:"id"`
}

func (q *Queries) RejectPaymentRequest(ctx context.Context, arg RejectPaymentRequestParams) (PaymentRequest, error) {
	row := q.db.QueryRow(ctx, rejectPaymentRequest, arg.RejectionReason, arg.ReviewedBy, arg.ID)
	var i PaymentRequest
	err := row.Scan(
		&i.ID,
		&i.RequestedBy,
		&i.ReviewedBy,
		&i.Amount,
		&i.Status,
		&i.Description,
		&i.RejectionReason,
		&i.BankCode,
		&i.AccountNumber,
		&i.AccountName,
		&i.ReviewedAt,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const updatePayoutStatus = `-- name: UpdatePayoutStatus :one
UPDATE payouts
SET status = $1,
    paid_at = CASE WHEN $1 = 'completed' THEN now() ELSE paid_at END
WHERE id = $2
RETURNING id, user_id, salary_code_id, amount, status, pay_period, paid_at, created_at
`

type UpdatePayoutStatusParams struct {
	Status string      `json:"status"`
	ID     pgtype.UUID `json:"id"`
}

func (q *Queries) UpdatePayoutStatus(ctx context.Context, arg UpdatePayoutStatusParams) (Payout, error) {
	row := q.db.QueryRow(ctx, updatePayoutStatus, arg.Status, arg.ID)
	var i Payout
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SalaryCodeID,
		&i.Amount,
		&i.Status,
		&i.PayPeriod,
		&i.PaidAt,
		&i.CreatedAt,
	)
	return i, err
}
