// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateEmployee(ctx context.Context, arg CreateEmployeeParams) (Employee, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteEmployee(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error)
	GetAllUsers(ctx context.Context, arg GetAllUsersParams) ([]User, error)
	GetEmployeeByUserID(ctx context.Context, userID pgtype.UUID) (Employee, error)
	GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	RevokeRefreshToken(ctx context.Context, tokenHash string) (RefreshToken, error)
	SoftDeleteUser(ctx context.Context, id pgtype.UUID) (User, error)
	UpdateEmployee(ctx context.Context, arg UpdateEmployeeParams) (Employee, error)
	// Partial update: unset (nil) args keep the existing value. Password is
	// excluded — that's UpdateUserPassword's job.
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (User, error)
}

var _ Querier = (*Queries)(nil)
