// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbq

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateEmployee(ctx context.Context, arg CreateEmployeeParams) (Employee, error)
	DeleteEmployee(ctx context.Context, id uuid.UUID) (uuid.UUID, error)
	GetEmployeeByUserID(ctx context.Context, userID uuid.UUID) (Employee, error)
	UpdateEmployee(ctx context.Context, arg UpdateEmployeeParams) (Employee, error)
}

var _ Querier = (*Queries)(nil)
