// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: salary_codes.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countEmployeesBySalaryCode = `-- name: CountEmployeesBySalaryCode :one
SELECT COUNT(*) FROM employees WHERE salary_code_id = $1
`

func (q *Queries) CountEmployeesBySalaryCode(ctx context.Context, salaryCodeID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countEmployeesBySalaryCode, salaryCodeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSalaryCodes = `-- name: CountSalaryCodes :one
SELECT COUNT(*) FROM salary_codes
WHERE ($1::text IS NULL OR level = $1)
`

func (q *Queries) CountSalaryCodes(ctx context.Context, level *string) (int64, error) {
	row := q.db.QueryRow(ctx, countSalaryCodes, level)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSalaryCode = `-- name: CreateSalaryCode :one
INSERT INTO salary_codes (code, level, amount)
VALUES ($1, $2, $3)
RETURNING id, code, level, amount
`

type CreateSalaryCodeParams struct {
	Code   string `json:"code"`
	Level  string `json:"level"`
	Amount int64  `json:"amount"`
}

func (q *Queries) CreateSalaryCode(ctx context.Context, arg CreateSalaryCodeParams) (SalaryCode, error) {
	row := q.db.QueryRow(ctx, createSalaryCode, arg.Code, arg.Level, arg.Amount)
	var i SalaryCode
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Level,
		&i.Amount,
	)
	return i, err
}

const deleteSalaryCode = `-- name: DeleteSalaryCode :one
DELETE FROM salary_codes WHERE id = $1
RETURNING id
`

func (q *Queries) DeleteSalaryCode(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, deleteSalaryCode, id)
	err := row.Scan(&id)
	return id, err
}

const getSalaryCodeByCode = `-- name: GetSalaryCodeByCode :one
SELECT id, code, level, amount FROM salary_codes WHERE code = $1
`

func (q *Queries) GetSalaryCodeByCode(ctx context.Context, code string) (SalaryCode, error) {
	row := q.db.QueryRow(ctx, getSalaryCodeByCode, code)
	var i SalaryCode
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Level,
		&i.Amount,
	)
	return i, err
}

const getSalaryCodeByID = `-- name: GetSalaryCodeByID :one
SELECT id, code, level, amount FROM salary_codes WHERE id = $1
`

func (q *Queries) GetSalaryCodeByID(ctx context.Context, id pgtype.UUID) (SalaryCode, error) {
	row := q.db.QueryRow(ctx, getSalaryCodeByID, id)
	var i SalaryCode
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Level,
		&i.Amount,
	)
	return i, err
}

const listSalaryCodes = `-- name: ListSalaryCodes :many
SELECT id, code, level, amount FROM salary_codes
WHERE ($3::text IS NULL OR level = $3)
ORDER BY level ASC, amount DESC
LIMIT $1 OFFSET $2
`

type ListSalaryCodesParams struct {
	Limit  int32   `json:"limit"`
	Offset int32   `json:"offset"`
	Level  *string `json:"level"`
}

func (q *Queries) ListSalaryCodes(ctx context.Context, arg ListSalaryCodesParams) ([]SalaryCode, error) {
	rows, err := q.db.Query(ctx, listSalaryCodes, arg.Limit, arg.Offset, arg.Level)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SalaryCode{}
	for rows.Next() {
		var i SalaryCode
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Level,
			&i.Amount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSalaryCode = `-- name: UpdateSalaryCode :one
UPDATE salary_codes
SET
  level  = COALESCE($1, level),
  amount = COALESCE($2, amount)
WHERE id = $3
RETURNING id, code, level, amount
`

type UpdateSalaryCodeParams struct {
	Level  *string     `json:"level"`
	Amount *int64      `json:"amount"`
	ID     pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateSalaryCode(ctx context.Context, arg UpdateSalaryCodeParams) (SalaryCode, error) {
	row := q.db.QueryRow(ctx, updateSalaryCode, arg.Level, arg.Amount, arg.ID)
	var i SalaryCode
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Level,
		&i.Amount,
	)
	return i, err
}
